# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Define the path to the Flutter SDK
flutter_root = ENV['FLUTTER_ROOT']

unless flutter_root && File.exist?(File.join(flutter_root, 'bin', 'flutter'))
  raise 'Flutter SDK not found. Please ensure FLUTTER_ROOT is set correctly.'
end

# Load the Flutter pod helper script
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  # Enables static linking to resolve module issues
  use_frameworks! :linkage => :static

  # Integrate Flutter dependencies
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)

  # Additional settings if needed
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable bitcode if necessary
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Set Swift version if required
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
